"""Standard MCP server catalog — reference integrations by functional domain."""

from __future__ import annotations

from typing import Any, Literal

IntegrationType = Literal["native", "stdio", "http"]
TransportType = Literal["native", "stdio", "http", "websocket"]

MCP_CATEGORIES: list[dict[str, str]] = [
    {"id": "engineering", "title": "Core Engineering & Local Environment", "emoji": "💻"},
    {"id": "databases", "title": "Databases & Storage Connectors", "emoji": "🗄️"},
    {"id": "web_search", "title": "Advanced Web Search & Scraping", "emoji": "🔍"},
    {"id": "communication", "title": "Communication & Workspace Integration", "emoji": "🤝"},
    {"id": "financial", "title": "Financial, Legal & Market Intelligence", "emoji": "📊"},
    {"id": "creative", "title": "Creative & Media Engines", "emoji": "🎨"},
    {"id": "discovery", "title": "Discovery & Registry", "emoji": "🧭"},
]

MCP_SERVERS: list[dict[str, Any]] = [
    # --- Engineering ---
    {
        "id": "filesystem",
        "name": "Filesystem",
        "description": "Secure local file operations (read, write, list, search) with configurable directory boundaries.",
        "category": "engineering",
        "integration": "native",
        "transport": "native",
        "endpoint": "native://filesystem",
        "tools": ["read_file", "write_file", "list_directory", "search_files"],
        "package": "@modelcontextprotocol/server-filesystem",
        "env_vars": [],
        "setup_note": "Built into CodeForge — uses workspace file tools.",
    },
    {
        "id": "git",
        "name": "Git",
        "description": "Deep repository analysis, branch management, code diff tracing, and commit sequencing.",
        "category": "engineering",
        "integration": "native",
        "transport": "native",
        "endpoint": "native://git",
        "tools": ["git_status", "git_diff", "git_log", "git_commit"],
        "package": "@modelcontextprotocol/server-git",
        "env_vars": [],
        "setup_note": "Built into CodeForge — git_status, git_diff, git_stage tools.",
    },
    {
        "id": "github",
        "name": "GitHub",
        "description": "Full GitHub integration for pull requests, issues, and CI/CD workflows.",
        "category": "engineering",
        "integration": "stdio",
        "transport": "stdio",
        "endpoint": "stdio://@modelcontextprotocol/server-github",
        "tools": ["create_pull_request", "create_issue", "search_repositories", "get_file_contents"],
        "package": "@modelcontextprotocol/server-github",
        "env_vars": ["GITHUB_PERSONAL_ACCESS_TOKEN"],
        "setup_note": "Set GITHUB_PERSONAL_ACCESS_TOKEN. PR creation also available natively.",
    },
    {
        "id": "gitlab",
        "name": "GitLab",
        "description": "GitLab merge requests, issues, and pipeline integration.",
        "category": "engineering",
        "integration": "stdio",
        "transport": "stdio",
        "endpoint": "stdio://@modelcontextprotocol/server-gitlab",
        "tools": ["create_merge_request", "create_issue", "list_projects", "get_file"],
        "package": "@modelcontextprotocol/server-gitlab",
        "env_vars": ["GITLAB_PERSONAL_ACCESS_TOKEN", "GITLAB_API_URL"],
        "setup_note": "Set GITLAB_PERSONAL_ACCESS_TOKEN and optional GITLAB_API_URL.",
    },
    {
        "id": "everything",
        "name": "Everything",
        "description": "Foundational reference server for testing prompts, mock tools, and custom endpoints.",
        "category": "engineering",
        "integration": "native",
        "transport": "native",
        "endpoint": "native://everything",
        "tools": ["echo", "add", "long_running_operation", "sample_image", "ping"],
        "package": "@modelcontextprotocol/server-everything",
        "env_vars": [],
        "setup_note": "Reference mock tools — ping available immediately.",
    },
    {
        "id": "puppeteer",
        "name": "Puppeteer",
        "description": "Headless browser automation — navigate pages, extract DOM trees, and take screenshots.",
        "category": "engineering",
        "integration": "stdio",
        "transport": "stdio",
        "endpoint": "stdio://@modelcontextprotocol/server-puppeteer",
        "tools": ["puppeteer_navigate", "puppeteer_screenshot", "puppeteer_click", "puppeteer_evaluate"],
        "package": "@modelcontextprotocol/server-puppeteer",
        "env_vars": [],
        "setup_note": "Requires Node.js and Chromium. Use fetch_url natively for simple pages.",
    },
    {
        "id": "sequential_thinking",
        "name": "Sequential Thinking",
        "description": "Break complex tasks into a multi-step dynamic thought log.",
        "category": "engineering",
        "integration": "native",
        "transport": "native",
        "endpoint": "native://sequential_thinking",
        "tools": ["sequentialthinking"],
        "package": "@modelcontextprotocol/server-sequential-thinking",
        "env_vars": [],
        "setup_note": "Built into CodeForge agent reasoning pipeline.",
    },
    {
        "id": "sentry",
        "name": "Sentry",
        "description": "Retrieve production error events and traces from Sentry.io for bug diagnosis.",
        "category": "engineering",
        "integration": "stdio",
        "transport": "stdio",
        "endpoint": "stdio://@modelcontextprotocol/server-sentry",
        "tools": ["list_issues", "get_issue_details", "list_events"],
        "package": "@modelcontextprotocol/server-sentry",
        "env_vars": ["SENTRY_AUTH_TOKEN", "SENTRY_ORG"],
        "setup_note": "Set SENTRY_AUTH_TOKEN and SENTRY_ORG.",
    },
    {
        "id": "time",
        "name": "Time",
        "description": "Time, timezone conversion, and system epoch synchronization.",
        "category": "engineering",
        "integration": "native",
        "transport": "native",
        "endpoint": "native://time",
        "tools": ["get_current_time", "convert_time"],
        "package": "@modelcontextprotocol/server-time",
        "env_vars": [],
        "setup_note": "Built-in time tools — no external server required.",
    },
    {
        "id": "appium",
        "name": "Appium",
        "description": "Mobile testing automation for iOS and Android simulated or physical devices.",
        "category": "engineering",
        "integration": "http",
        "transport": "http",
        "endpoint": "http://localhost:4723/mcp",
        "tools": ["find_element", "click", "send_keys", "get_page_source"],
        "package": "appium-mcp",
        "env_vars": ["APPIUM_SERVER_URL"],
        "setup_note": "Run Appium server locally and point APPIUM_SERVER_URL.",
    },
    # --- Databases ---
    {
        "id": "postgresql",
        "name": "PostgreSQL",
        "description": "Read/write database access with query running and table structure scanning.",
        "category": "databases",
        "integration": "stdio",
        "transport": "stdio",
        "endpoint": "stdio://@modelcontextprotocol/server-postgres",
        "tools": ["query", "list_tables", "describe_table"],
        "package": "@modelcontextprotocol/server-postgres",
        "env_vars": ["DATABASE_URL"],
        "setup_note": "Set DATABASE_URL to your Postgres connection string.",
    },
    {
        "id": "sqlite",
        "name": "SQLite",
        "description": "Local relational database integration for BI queries and file-based lookups.",
        "category": "databases",
        "integration": "stdio",
        "transport": "stdio",
        "endpoint": "stdio://@modelcontextprotocol/server-sqlite",
        "tools": ["read_query", "write_query", "list_tables", "describe_table"],
        "package": "@modelcontextprotocol/server-sqlite",
        "env_vars": ["SQLITE_DB_PATH"],
        "setup_note": "Set SQLITE_DB_PATH to your .db file path.",
    },
    {
        "id": "redis",
        "name": "Redis",
        "description": "Real-time caching layer monitoring and key-value interaction.",
        "category": "databases",
        "integration": "stdio",
        "transport": "stdio",
        "endpoint": "stdio://@modelcontextprotocol/server-redis",
        "tools": ["get", "set", "delete", "list_keys"],
        "package": "@modelcontextprotocol/server-redis",
        "env_vars": ["REDIS_URL"],
        "setup_note": "Set REDIS_URL (e.g. redis://localhost:6379).",
    },
    {
        "id": "arcedb",
        "name": "ArcadeDB",
        "description": "Multi-model graph and vector database supporting SQL, Cypher, and Gremlin.",
        "category": "databases",
        "integration": "http",
        "transport": "http",
        "endpoint": "http://localhost:2480/mcp",
        "tools": ["query", "create_vertex", "create_edge"],
        "package": "arcedb-mcp",
        "env_vars": ["ARCADEDB_URL", "ARCADEDB_USER", "ARCADEDB_PASSWORD"],
        "setup_note": "Point to your ArcadeDB HTTP endpoint.",
    },
    {
        "id": "google_drive",
        "name": "Google Drive",
        "description": "File extraction, folder parsing, and cloud document indexing.",
        "category": "databases",
        "integration": "stdio",
        "transport": "stdio",
        "endpoint": "stdio://@modelcontextprotocol/server-gdrive",
        "tools": ["search_files", "read_file", "list_files"],
        "package": "@modelcontextprotocol/server-gdrive",
        "env_vars": ["GDRIVE_CREDENTIALS_PATH"],
        "setup_note": "OAuth credentials required via GDRIVE_CREDENTIALS_PATH.",
    },
    # --- Web Search ---
    {
        "id": "web_search",
        "name": "Web Search (built-in)",
        "description": "Free web search via Stack Overflow, Wikipedia, MDN, and DuckDuckGo — no API key.",
        "category": "web_search",
        "integration": "native",
        "transport": "native",
        "endpoint": "native://web_search",
        "tools": ["web_search", "fetch_url"],
        "package": None,
        "env_vars": [],
        "setup_note": "Built into CodeForge — replaces paid search APIs.",
    },
    {
        "id": "agent_reach",
        "name": "Agent Reach (server)",
        "description": "Server-safe internet research — Jina web reader, YouTube subtitles, RSS feeds, and public GitHub repos.",
        "category": "web_search",
        "integration": "native",
        "transport": "native",
        "endpoint": "native://agent_reach",
        "tools": ["fetch_web", "youtube_transcript", "rss_read", "github_repo"],
        "package": None,
        "env_vars": [
            "CODEFORGE_AGENT_REACH_WEB",
            "CODEFORGE_AGENT_REACH_YOUTUBE",
            "CODEFORGE_AGENT_REACH_RSS",
            "CODEFORGE_AGENT_REACH_GITHUB",
        ],
        "setup_note": "Server-safe channels only. Enable agent-reach skill for Twitter/Reddit/XHS via local CLI.",
    },
    {
        "id": "brave_search",
        "name": "Brave Search",
        "description": "Official Brave Search API for fast structured web and local results.",
        "category": "web_search",
        "integration": "stdio",
        "transport": "stdio",
        "endpoint": "stdio://@modelcontextprotocol/server-brave-search",
        "tools": ["brave_web_search", "brave_local_search"],
        "package": "@modelcontextprotocol/server-brave-search",
        "env_vars": ["BRAVE_API_KEY"],
        "setup_note": "Optional — requires BRAVE_API_KEY. Free built-in search is available.",
    },
    {
        "id": "perplexity",
        "name": "Perplexity Ask",
        "description": "Perplexity API for deeply synthesized web answers inside the conversation.",
        "category": "web_search",
        "integration": "http",
        "transport": "http",
        "endpoint": "https://api.perplexity.ai/mcp",
        "tools": ["perplexity_ask", "perplexity_search"],
        "package": "perplexity-mcp",
        "env_vars": ["PERPLEXITY_API_KEY"],
        "setup_note": "Set PERPLEXITY_API_KEY from perplexity.ai.",
    },
    {
        "id": "firecrawl",
        "name": "Firecrawl",
        "description": "Full web-scraping engine converting JS-heavy sites into clean Markdown.",
        "category": "web_search",
        "integration": "stdio",
        "transport": "stdio",
        "endpoint": "stdio://firecrawl-mcp",
        "tools": ["scrape", "crawl", "map"],
        "package": "firecrawl-mcp",
        "env_vars": ["FIRECRAWL_API_KEY"],
        "setup_note": "Set FIRECRAWL_API_KEY from firecrawl.dev.",
    },
    {
        "id": "serper",
        "name": "Serper",
        "description": "Google Search wrapper providing raw SERP, local maps, and image data.",
        "category": "web_search",
        "integration": "stdio",
        "transport": "stdio",
        "endpoint": "stdio://serper-mcp",
        "tools": ["google_search", "google_maps", "google_images"],
        "package": "serper-mcp-server",
        "env_vars": ["SERPER_API_KEY"],
        "setup_note": "Set SERPER_API_KEY from serper.dev.",
    },
    {
        "id": "jina_search",
        "name": "Jina AI Search",
        "description": "Jina search foundation APIs for deep web reading and retrieval.",
        "category": "web_search",
        "integration": "http",
        "transport": "http",
        "endpoint": "https://api.jina.ai/mcp",
        "tools": ["jina_search", "jina_reader"],
        "package": "jina-mcp",
        "env_vars": ["JINA_API_KEY"],
        "setup_note": "Set JINA_API_KEY from jina.ai.",
    },
    {
        "id": "hasdata",
        "name": "HasData",
        "description": "Bridges to 40+ scraping channels covering Amazon, Google Maps, and social feeds.",
        "category": "web_search",
        "integration": "http",
        "transport": "http",
        "endpoint": "https://api.hasdata.com/mcp",
        "tools": ["scrape_amazon", "scrape_maps", "scrape_social"],
        "package": "hasdata-mcp",
        "env_vars": ["HASDATA_API_KEY"],
        "setup_note": "Set HASDATA_API_KEY from hasdata.com.",
    },
    # --- Communication ---
    {
        "id": "slack",
        "name": "Slack",
        "description": "Read/write messages, create channels, search archives, and alert teams.",
        "category": "communication",
        "integration": "stdio",
        "transport": "stdio",
        "endpoint": "stdio://@modelcontextprotocol/server-slack",
        "tools": ["post_message", "list_channels", "search_messages", "get_channel_history"],
        "package": "@modelcontextprotocol/server-slack",
        "env_vars": ["SLACK_BOT_TOKEN", "SLACK_TEAM_ID"],
        "setup_note": "Create a Slack app and set SLACK_BOT_TOKEN.",
    },
    {
        "id": "jira",
        "name": "Jira",
        "description": "Project management — create tickets, update sprints, summarize blockers.",
        "category": "communication",
        "integration": "stdio",
        "transport": "stdio",
        "endpoint": "stdio://@modelcontextprotocol/server-jira",
        "tools": ["create_issue", "update_issue", "search_issues", "get_sprint"],
        "package": "@modelcontextprotocol/server-jira",
        "env_vars": ["JIRA_URL", "JIRA_EMAIL", "JIRA_API_TOKEN"],
        "setup_note": "Set JIRA_URL, JIRA_EMAIL, and JIRA_API_TOKEN.",
    },
    {
        "id": "notion",
        "name": "Notion",
        "description": "Full workspace integration for documentation and meeting transcripts.",
        "category": "communication",
        "integration": "stdio",
        "transport": "stdio",
        "endpoint": "stdio://@modelcontextprotocol/server-notion",
        "tools": ["search", "read_page", "create_page", "update_page"],
        "package": "@modelcontextprotocol/server-notion",
        "env_vars": ["NOTION_API_KEY"],
        "setup_note": "Set NOTION_API_KEY from notion.so/integrations.",
    },
    {
        "id": "mailbridge",
        "name": "Mailbridge",
        "description": "Local email via IMAP/SMTP — filter, read, and write emails.",
        "category": "communication",
        "integration": "stdio",
        "transport": "stdio",
        "endpoint": "stdio://mailbridge-mcp",
        "tools": ["list_messages", "read_message", "send_message", "search_mailbox"],
        "package": "mailbridge-mcp",
        "env_vars": ["IMAP_HOST", "SMTP_HOST", "EMAIL_USER", "EMAIL_PASSWORD"],
        "setup_note": "Configure IMAP/SMTP credentials for your mailbox.",
    },
    # --- Financial ---
    {
        "id": "alphavantage",
        "name": "AlphaVantage",
        "description": "Real-time stock quotes, historical equity values, and financial indicators.",
        "category": "financial",
        "integration": "stdio",
        "transport": "stdio",
        "endpoint": "stdio://alphavantage-mcp",
        "tools": ["get_quote", "get_daily", "get_indicator"],
        "package": "alphavantage-mcp",
        "env_vars": ["ALPHAVANTAGE_API_KEY"],
        "setup_note": "Free API key from alphavantage.co.",
    },
    {
        "id": "flox",
        "name": "Flox",
        "description": "Quantitative trading framework with backtesting and order execution hooks.",
        "category": "financial",
        "integration": "http",
        "transport": "http",
        "endpoint": "http://localhost:8765/mcp",
        "tools": ["backtest", "get_positions", "place_order"],
        "package": "flox-mcp",
        "env_vars": ["FLOX_API_KEY"],
        "setup_note": "Run Flox locally and set FLOX_API_KEY.",
    },
    {
        "id": "dodo_payments",
        "name": "Dodo Payments",
        "description": "Manage subscriptions, refunds, and live client usage via secure OAuth.",
        "category": "financial",
        "integration": "http",
        "transport": "http",
        "endpoint": "https://api.dodopayments.com/mcp",
        "tools": ["list_subscriptions", "create_refund", "get_usage"],
        "package": "dodo-payments-mcp",
        "env_vars": ["DODO_API_KEY"],
        "setup_note": "OAuth credentials from Dodo Payments dashboard.",
    },
    {
        "id": "datanexus",
        "name": "DataNexus",
        "description": "Public data engine for CVE logs, patent entries, and corporate contracts.",
        "category": "financial",
        "integration": "http",
        "transport": "http",
        "endpoint": "https://api.datanexus.io/mcp",
        "tools": ["search_cve", "search_patents", "search_contracts"],
        "package": "datanexus-mcp",
        "env_vars": ["DATANEXUS_API_KEY"],
        "setup_note": "Set DATANEXUS_API_KEY from datanexus.io.",
    },
    # --- Creative ---
    {
        "id": "flux_ai",
        "name": "Flux AI (MCPFlux)",
        "description": "Generate and textually refine images using Black Forest Labs models.",
        "category": "creative",
        "integration": "http",
        "transport": "http",
        "endpoint": "https://api.mcpflux.ai/mcp",
        "tools": ["generate_image", "refine_image"],
        "package": "mcpflux",
        "env_vars": ["FLUX_API_KEY"],
        "setup_note": "Set FLUX_API_KEY from Black Forest Labs / MCPFlux.",
    },
    {
        "id": "minimax",
        "name": "MiniMax MCP",
        "description": "Voice cloning, advanced video creation, and text-to-speech generation.",
        "category": "creative",
        "integration": "http",
        "transport": "http",
        "endpoint": "https://api.minimax.chat/mcp",
        "tools": ["text_to_speech", "voice_clone", "create_video"],
        "package": "minimax-mcp",
        "env_vars": ["MINIMAX_API_KEY"],
        "setup_note": "Set MINIMAX_API_KEY from minimax.chat.",
    },
    {
        "id": "manim",
        "name": "Manim MCP",
        "description": "Render localized visual math animations using Python code generation.",
        "category": "creative",
        "integration": "stdio",
        "transport": "stdio",
        "endpoint": "stdio://manim-mcp",
        "tools": ["render_animation", "preview_scene"],
        "package": "manim-mcp",
        "env_vars": [],
        "setup_note": "Requires Python manim library installed locally.",
    },
    {
        "id": "open_library",
        "name": "Open Library",
        "description": "Search and parse semantic data over thousands of books.",
        "category": "creative",
        "integration": "native",
        "transport": "native",
        "endpoint": "native://open_library",
        "tools": ["search_books", "get_book_details"],
        "package": "open-library-mcp",
        "env_vars": [],
        "setup_note": "Uses Open Library public API — no key required.",
    },
    # --- Discovery ---
    {
        "id": "a2asearch",
        "name": "A2A Search MCP",
        "description": "Discovery tool to scan the growing index of thousands of custom MCP utilities.",
        "category": "discovery",
        "integration": "stdio",
        "transport": "stdio",
        "endpoint": "stdio://a2asearch-mcp",
        "tools": ["search_mcp_servers", "get_server_details"],
        "package": "a2asearch-mcp",
        "env_vars": [],
        "setup_note": "Run: npx -y a2asearch-mcp to discover community servers.",
    },
]

_SERVER_BY_ID = {item["id"]: item for item in MCP_SERVERS}


def list_categories() -> list[dict[str, str]]:
    return list(MCP_CATEGORIES)


def list_servers(*, category: str | None = None) -> list[dict[str, Any]]:
    from .catalog_versions import catalog_version_for

    if not category:
        return [{**dict(item), "version": catalog_version_for(item)} for item in MCP_SERVERS]
    return [
        {**dict(item), "version": catalog_version_for(item)}
        for item in MCP_SERVERS
        if item["category"] == category
    ]


def get_server(server_id: str) -> dict[str, Any] | None:
    row = _SERVER_BY_ID.get(server_id)
    return dict(row) if row else None


def servers_for_category(category_id: str) -> list[dict[str, Any]]:
    return list_servers(category=category_id)
